//Redefinitions
#define console Serial
#define i2c Wire
#define sleep delay
//Wiring lowercase
#define digitalwrite digitalWrite
#define digitalread digitalRead
#define analogwrite analogWrite
#define analogread analogRead
#define analogreference analogReference
#define analogreadresolution analogReadResolution
#define analogwriteresolution analogWriteResolution
#define notone noTone
#define pulsein pulseIn
#define pulseinlong pulseInLong
#define shiftin shiftIn
#define shiftout shiftOut
#define delaymicroseconds delayMicroseconds
#define isalpha isAlpha
#define isalphanumeric isAlphaNumeric
#define iscontrol isControl
#define isdigit isDigit
#define isgraph isGraph
#define ishexadecimaldigit isHexadecimalDigit
#define islowercase isLowerCase
#define isprintable isPrintable
#define ispunct isPunct
#define isspace isSpace
#define isuppercase isUpperCase
#define iswhitespace isWhiteSpace
#define pinmode pinMode
#define low LOW
#define high HIGH
#define output OUTPUT
#define input INPUT
#define input_pullup INPUT_PULLUP
#define led_builtin LED_BUILTIN
#define progmem PROGMEM
#define keyboard Keyboard
#define mouse Mouse
#define randomseed randomSeed
#define bitclear bitClear
#define bitread bitRead
#define bitset bitSet
#define bitwrite bitWrite
#define highbytes highBytes
#define lowbytes lowBytes
#define attachinterrupt attachInterrupt
#define detachinterrupt detachInterrupt
#define nointerrupts noInterrupts
//Text operators
#define same ==
#define different !=
#define greater >
#define lesser <
#define greaterthanequal >=
#define lesserthanequal <=